name: Process

on:
  pull_request:
    branches:
    - main  # Or the name of your main branch

jobs:
  find_and_process_file:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10' 